config/routes.rb
Arels::Application.routes.draw do
  resources :virtual_tours

  resources :offices

  resources :properties

  resources :listing_data

  resources :members
  
  root :to => 'properties#listings'

end

app/models/property.rb
class Property < ActiveRecord::Base
  set_primary_key :MA_TECH_ID
  belongs_to :Member
  has_one :VirtualTour
  paginates_per 5
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :agent_settings
  layout :set_layout

  def listings
    @properties = Property.where(:ME_TECH_ID => @agent_id).page params[:page]
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @properties }
    end
  end

  def show
    @property = Property.find(params[:id])
      format.html # show.html.erb
      format.xml  { render :xml => @property }
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def getRooms(room)
    if room == "" then
      room = "Master Bedroom:M|0||||;1/2 Bath:M|0||||;Bedroom 2:M|3||||;Family Room:M|1||||Great Room;Kitchen:M|1||||;Dining Room:M|1||||;Laundry Room:M|1||||;Full Baths:M|2||||;"
    end
    debugger
    @rooms = room.split(";")
    @room = @rooms[1].split(":")
    @spaces = @room[1].gsub!(/([|])/,' |')
    @attribute = @room[1].split("|")
    @room_number = @attribute[1]
  end
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/listings.html.erb
<table cellpadding="0px" cellspacing="0px">
<% @properties.each do |properties| %>
  <tr style="width:30px;">
    <td><font face="times, times new roman, serif" size="4">MLS# <%= properties.PREFIX %>-<%= properties.LIST_NBR %></font></td>
  </tr>
  <tr>
    <td><img alt="Image" style="padding:5px 5px 5px 5px;" border="1" width="200px" height="150px" src="/images/<%= properties.PREFIX %>/<%= properties.LIST_NBR %>/<%= properties.PREFIX %>-<%= properties.LIST_NBR %>_1.jpg"><br />
      <center><%= submit_tag "View Details", :class => "button", :action => "show" %>&nbsp;&nbsp;<%= submit_tag "Add To Favorites", :class => "button" %></center>
    </td>
    
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td valign="top">
      <b><font size="4">Price:&nbsp;<%=h number_to_currency properties.LIST_PRICE, :precision => 0 %></font></b><br />
      <%= properties.AREA %><br />
      <b>Bedrooms:&nbsp;<%= getRooms(properties.ROOMS) %> Bathrooms:</b><br />
      <b>Type:</b>&nbsp;<%= properties.BOOK_SEC %><br />
      <b>Details:</b><br />
      <div style="width:350px;"><%= truncate(properties.REMARK1, :length => 173, :omission => '...') %></div><br />
    </td>
  </tr>
  <tr>
    <td style="width:150px;"><br /></td>
  </tr>
<% end %>
</table>
<%= paginate @properties %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>