config/routes.rb
Arels::Application.routes.draw do
  resources :virtual_tours

  resources :offices

  resources :properties

  resources :listing_data

  resources :members
  
  root :to => 'properties#listings'

end

app/models/virtual_tour.rb
class VirtualTour < ActiveRecord::Base
  set_primary_key :PropertyID
  belongs_to :Property
end

app/controllers/virtual_tours_controller.rb
class VirtualToursController < ApplicationController
  # GET /virtual_tours
  # GET /virtual_tours.xml
  def index
    @virtual_tours = VirtualTour.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @virtual_tours }
    end
  end

  # GET /virtual_tours/1
  # GET /virtual_tours/1.xml
  def show
    @virtual_tour = VirtualTour.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @virtual_tour }
    end
  end

  # GET /virtual_tours/new
  # GET /virtual_tours/new.xml
  def new
    @virtual_tour = VirtualTour.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @virtual_tour }
    end
  end

  # GET /virtual_tours/1/edit
  def edit
    @virtual_tour = VirtualTour.find(params[:id])
  end

  # POST /virtual_tours
  # POST /virtual_tours.xml
  def create
    @virtual_tour = VirtualTour.new(params[:virtual_tour])

    respond_to do |format|
      if @virtual_tour.save
        format.html { redirect_to(@virtual_tour, :notice => 'Virtual tour was successfully created.') }
        format.xml  { render :xml => @virtual_tour, :status => :created, :location => @virtual_tour }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @virtual_tour.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /virtual_tours/1
  # PUT /virtual_tours/1.xml
  def update
    @virtual_tour = VirtualTour.find(params[:id])

    respond_to do |format|
      if @virtual_tour.update_attributes(params[:virtual_tour])
        format.html { redirect_to(@virtual_tour, :notice => 'Virtual tour was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @virtual_tour.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /virtual_tours/1
  # DELETE /virtual_tours/1.xml
  def destroy
    @virtual_tour = VirtualTour.find(params[:id])
    @virtual_tour.destroy

    respond_to do |format|
      format.html { redirect_to(virtual_tours_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/virtual_tours_helper.rb
module VirtualToursHelper
end

app/views/virtual_tours/_form.html.erb
<%= form_for(@virtual_tour) do |f| %>
  <% if @virtual_tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@virtual_tour.errors.count, "error") %> prohibited this virtual_tour from being saved:</h2>

      <ul>
      <% @virtual_tour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/virtual_tours/edit.html.erb
<h1>Editing virtual_tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @virtual_tour %> |
<%= link_to 'Back', virtual_tours_path %>

app/views/virtual_tours/index.html.erb
<h1>Listing virtual_tours</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @virtual_tours.each do |virtual_tour| %>
  <tr>
    <td><%= link_to 'Show', virtual_tour %></td>
    <td><%= link_to 'Edit', edit_virtual_tour_path(virtual_tour) %></td>
    <td><%= link_to 'Destroy', virtual_tour, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Virtual tour', new_virtual_tour_path %>

app/views/virtual_tours/new.html.erb
<h1>New virtual_tour</h1>

<%= render 'form' %>

<%= link_to 'Back', virtual_tours_path %>

app/views/virtual_tours/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_virtual_tour_path(@virtual_tour) %> |
<%= link_to 'Back', virtual_tours_path %>